In [ ]:
!pip install -q wordcloud
import wordcloud

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [ ]:
import nltk
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import io
import unicodedata
import numpy as np
import re
import string

In [ ]:

import pandas as pd
import re
import nltk
import spacy
import string
pd.options.mode.chained_assignment = None

full_df = pd.read_csv("/content/Restaurant reviews.csv", nrows=1000)

full_df.head(20)

,Restaurant,Reviewer,Review,Rating,Metadata,Time,Pictures
0,Beyond Flavours,Rusha Chakraborty,"The ambience was good, food was quite good . h...",5.0,"1 Review , 2 Followers",5/25/2019 15:54,0
1,Beyond Flavours,Anusha Tirumalaneedi,Ambience is too good for a pleasant evening. S...,5.0,"3 Reviews , 2 Followers",5/25/2019 14:20,0
2,Beyond Flavours,Ashok Shekhawat,A must try.. great food great ambience. Thnx f...,5.0,"2 Reviews , 3 Followers",5/24/2019 22:54,0
3,Beyond Flavours,Swapnil Sarkar,Soumen das and Arun was a great guy. Only beca...,5.0,"1 Review , 1 Follower",5/24/2019 22:11,0
4,Beyond Flavours,Dileep,Food is good.we ordered Kodi drumsticks and ba...,5.0,"3 Reviews , 2 Followers",5/24/2019 21:37,0
5,Beyond Flavours,Nagabhavani K,"Ambiance is good, service is good, food is aPr...",5.0,1 Review,5/24/2019 15:22,0
6,Beyond Flavours,Jamuna Bhuwalka,"Its a very nice place, ambience is different, ...",5.0,1 Review,5/24/2019 1:02,0
7,Beyond Flavours,Sandhya S,Well after reading so many reviews finally vis...,4.0,1 Review,5/23/2019 15:01,0
8,Beyond Flavours,Akash Thorat,"Excellent food , specially if you like spicy f...",5.0,"1 Review , 1 Follower",5/22/2019 23:12,0
9,Beyond Flavours,Smarak Patnaik,Came for the birthday treat of a close friend....,5.0,"1 Review , 1 Follower",5/22/2019 22:37,0
10,Beyond Flavours,Saubhagya Bhuyan,The service was great and the food was awesome...,5.0,"1 Review , 1 Follower",5/22/2019 22:22,0
11,Beyond Flavours,Srivaths07,"Very good ambience, amazing food ,good service...",5.0,"3 Reviews , 1 Follower",5/22/2019 21:43,0
12,Beyond Flavours,Kunj Mishra,Food was very good. Soup was as expected. In s...,5.0,"1 Review , 1 Follower",5/22/2019 21:29,0
13,Beyond Flavours,Pradeep Vetapalem,Food is too good. Telangana kodiak fry is must...,5.0,"2 Reviews , 25 Followers",5/22/2019 21:21,0
14,Beyond Flavours,Kankaria.ritu,"We ordered corn cheese balls, manchow soup and...",1.0,1 Review,5/22/2019 21:19,0
15,Beyond Flavours,Abhay Sharma,Food and ambience is fantastic.. Waiter Manav ...,5.0,"4 Reviews , 7 Followers",5/22/2019 20:38,0
16,Beyond Flavours,Shubham Jaiswal,Came here for lunch and the food was good and ...,4.0,"30 Reviews , 34 Followers",5/22/2019 19:54,8
17,Beyond Flavours,Srijani Mukherjee,The best thing about this place is the food. M...,5.0,"6 Reviews , 267 Followers",5/22/2019 19:47,1
18,Beyond Flavours,Hari Jangam,Polite and friendly staff. Nice ambience and g...,5.0,"1 Review , 1 Follower",5/22/2019 15:13,0
19,Beyond Flavours,Suneet Soni,Food is really good. We had vegetarian items i...,5.0,"1 Review , 33 Followers",5/21/2019 22:08,0

In [ ]:
df=full_df[['Reviewer','Review','Rating','Metadata'	]]
df.head()

,Reviewer,Review,Rating,Metadata
0,Rusha Chakraborty,"The ambience was good, food was quite good . h...",5.0,"1 Review , 2 Followers"
1,Anusha Tirumalaneedi,Ambience is too good for a pleasant evening. S...,5.0,"3 Reviews , 2 Followers"
2,Ashok Shekhawat,A must try.. great food great ambience. Thnx f...,5.0,"2 Reviews , 3 Followers"
3,Swapnil Sarkar,Soumen das and Arun was a great guy. Only beca...,5.0,"1 Review , 1 Follower"
4,Dileep,Food is good.we ordered Kodi drumsticks and ba...,5.0,"3 Reviews , 2 Followers"

In [ ]:
df.isna().sum()

Reviewer    0
Review      0
Rating      0
Metadata    0
dtype: int64

In [ ]:
df = full_df[["Review"]]
df["Review"] = df["Review"].astype(str)
df.head()

                                              Review
0  The ambience was good, food was quite good . h...
1  Ambience is too good for a pleasant evening. S...
2  A must try.. great food great ambience. Thnx f...
3  Soumen das and Arun was a great guy. Only beca...
4  Food is good.we ordered Kodi drumsticks and ba...

In [ ]:
df["Review_lower"] = df["Review"].str.lower()
df.head()

,Review,Review_lower
0,"The ambience was good, food was quite good . h...","the ambience was good, food was quite good . h..."
1,Ambience is too good for a pleasant evening. S...,ambience is too good for a pleasant evening. s...
2,A must try.. great food great ambience. Thnx f...,a must try.. great food great ambience. thnx f...
3,Soumen das and Arun was a great guy. Only beca...,soumen das and arun was a great guy. only beca...
4,Food is good.we ordered Kodi drumsticks and ba...,food is good.we ordered kodi drumsticks and ba...

In [ ]:


PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["Review_lo_punct"] = df["Review_lower"].apply(lambda text: remove_punctuation(text))
df.head()

,Review,Review_lower,Review_lo_punct
0,"The ambience was good, food was quite good . h...","the ambience was good, food was quite good . h...",the ambience was good food was quite good had...
1,Ambience is too good for a pleasant evening. S...,ambience is too good for a pleasant evening. s...,ambience is too good for a pleasant evening se...
2,A must try.. great food great ambience. Thnx f...,a must try.. great food great ambience. thnx f...,a must try great food great ambience thnx for ...
3,Soumen das and Arun was a great guy. Only beca...,soumen das and arun was a great guy. only beca...,soumen das and arun was a great guy only becau...
4,Food is good.we ordered Kodi drumsticks and ba...,food is good.we ordered kodi drumsticks and ba...,food is goodwe ordered kodi drumsticks and bas...

In [ ]:
df.drop(["Review_lower"], axis=1, inplace=True)
df

,Review,Review_lo_punct
0,"The ambience was good, food was quite good . h...",the ambience was good food was quite good had...
1,Ambience is too good for a pleasant evening. S...,ambience is too good for a pleasant evening se...
2,A must try.. great food great ambience. Thnx f...,a must try great food great ambience thnx for ...
3,Soumen das and Arun was a great guy. Only beca...,soumen das and arun was a great guy only becau...
4,Food is good.we ordered Kodi drumsticks and ba...,food is goodwe ordered kodi drumsticks and bas...
...,...,...
995,not ggod,not ggod
996,They didn't packed the ice cream nicely ie.. d...,they didnt packed the ice cream nicely ie didn...
997,ice cream was melted before it reached me and ...,ice cream was melted before it reached me and ...
998,"Ice cream was good , but it's totally got melt...",ice cream was good but its totally got melt a...
999,1.Half of ice cream spilled inside the package...,1half of ice cream spilled inside the package ...

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mustn't, needn, needn't, shan, shan't, shouldn, shouldn't, wasn, wasn't, weren, weren't, won, won't, wouldn, wouldn't"

In [ ]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df["Review_wo_stop"] = df["Review_lo_punct"].apply(lambda text: remove_stopwords(text))
df.head()

,Review,Review_lo_punct,Review_wo_stop
0,"The ambience was good, food was quite good . h...",the ambience was good food was quite good had...,ambience good food quite good saturday lunch c...
1,Ambience is too good for a pleasant evening. S...,ambience is too good for a pleasant evening se...,ambience good pleasant evening service prompt ...
2,A must try.. great food great ambience. Thnx f...,a must try great food great ambience thnx for ...,must try great food great ambience thnx servic...
3,Soumen das and Arun was a great guy. Only beca...,soumen das and arun was a great guy only becau...,soumen das arun great guy behavior sincerety g...
4,Food is good.we ordered Kodi drumsticks and ba...,food is goodwe ordered kodi drumsticks and bas...,food goodwe ordered kodi drumsticks basket mut...

In [ ]:
from collections import Counter
cnt = Counter()
for text in df["Review_wo_stop"].values:
    for word in text.split():
        cnt[word] += 1
        
cnt.most_common(10)

[('good', 794),
 ('food', 724),
 ('place', 562),
 ('service', 393),
 ('chicken', 287),
 ('great', 254),
 ('ambience', 240),
 ('one', 217),
 ('taste', 212),
 ('ordered', 207)]

In [ ]:
FREQWORDS = set([w for (w, wc) in cnt.most_common(10)])
def remove_freqwords(text):
    """custom function to remove the frequent words"""
    return " ".join([word for word in str(text).split() if word not in FREQWORDS])

df["Review_wo_stopfreq"] = df["Review_wo_stop"].apply(lambda text: remove_freqwords(text))
df.head()

,Review,Review_lo_punct,Review_wo_stop,Review_wo_stopfreq
0,"The ambience was good, food was quite good . h...",the ambience was good food was quite good had...,ambience good food quite good saturday lunch c...,quite saturday lunch cost effective sate brunc...
1,Ambience is too good for a pleasant evening. S...,ambience is too good for a pleasant evening se...,ambience good pleasant evening service prompt ...,pleasant evening prompt experience soumen das ...
2,A must try.. great food great ambience. Thnx f...,a must try great food great ambience thnx for ...,must try great food great ambience thnx servic...,must try thnx pradeep subroto personal recomme...
3,Soumen das and Arun was a great guy. Only beca...,soumen das and arun was a great guy only becau...,soumen das arun great guy behavior sincerety g...,soumen das arun guy behavior sincerety course ...
4,Food is good.we ordered Kodi drumsticks and ba...,food is goodwe ordered kodi drumsticks and bas...,food goodwe ordered kodi drumsticks basket mut...,goodwe kodi drumsticks basket mutton biryani t...

In [ ]:

n_rare_words = 10
RAREWORDS = set([w for (w, wc) in cnt.most_common()[:-n_rare_words-1:-1]])
def remove_rarewords(text):
    """custom function to remove the rare words"""
    return " ".join([word for word in str(text).split() if word not in RAREWORDS])

df["Review_wo_stopfreqrare"] = df["Review_wo_stopfreq"].apply(lambda text: remove_rarewords(text))
df.head()

,Review,Review_lo_punct,Review_wo_stop,Review_wo_stopfreq,Review_wo_stopfreqrare
0,"The ambience was good, food was quite good . h...",the ambience was good food was quite good had...,ambience good food quite good saturday lunch c...,quite saturday lunch cost effective sate brunc...,quite saturday lunch cost effective sate brunc...
1,Ambience is too good for a pleasant evening. S...,ambience is too good for a pleasant evening se...,ambience good pleasant evening service prompt ...,pleasant evening prompt experience soumen das ...,pleasant evening prompt experience soumen das ...
2,A must try.. great food great ambience. Thnx f...,a must try great food great ambience thnx for ...,must try great food great ambience thnx servic...,must try thnx pradeep subroto personal recomme...,must try thnx pradeep subroto personal recomme...
3,Soumen das and Arun was a great guy. Only beca...,soumen das and arun was a great guy only becau...,soumen das arun great guy behavior sincerety g...,soumen das arun guy behavior sincerety course ...,soumen das arun guy behavior sincerety course ...
4,Food is good.we ordered Kodi drumsticks and ba...,food is goodwe ordered kodi drumsticks and bas...,food goodwe ordered kodi drumsticks basket mut...,goodwe kodi drumsticks basket mutton biryani t...,goodwe kodi drumsticks basket mutton biryani t...

In [ ]:
df.drop(["Review_lo_punct", "Review_wo_stop"], axis=1, inplace=True)
df

,Review,Review_wo_stopfreq,Review_wo_stopfreqrare
0,"The ambience was good, food was quite good . h...",quite saturday lunch cost effective sate brunc...,quite saturday lunch cost effective sate brunc...
1,Ambience is too good for a pleasant evening. S...,pleasant evening prompt experience soumen das ...,pleasant evening prompt experience soumen das ...
2,A must try.. great food great ambience. Thnx f...,must try thnx pradeep subroto personal recomme...,must try thnx pradeep subroto personal recomme...
3,Soumen das and Arun was a great guy. Only beca...,soumen das arun guy behavior sincerety course ...,soumen das arun guy behavior sincerety course ...
4,Food is good.we ordered Kodi drumsticks and ba...,goodwe kodi drumsticks basket mutton biryani t...,goodwe kodi drumsticks basket mutton biryani t...
...,...,...,...
995,not ggod,ggod,ggod
996,They didn't packed the ice cream nicely ie.. d...,didnt packed ice cream nicely ie didnt keep dr...,didnt packed ice cream nicely ie didnt keep dr...
997,ice cream was melted before it reached me and ...,ice cream melted reached didnt see dry ice pie...,ice cream melted reached didnt see dry ice pie...
998,"Ice cream was good , but it's totally got melt...",ice cream totally got melt delivery boy took l...,ice cream totally got melt delivery boy took l...
999,1.Half of ice cream spilled inside the package...,1half ice cream spilled inside package 2i care...,ice cream inside package got brownie ice cream...

#**stemming**

In [ ]:
from nltk.stem.porter import PorterStemmer

# Drop the two columns 
df.drop(["Review_wo_stopfreq", "Review_wo_stopfreqrare"], axis=1, inplace=True) 

stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df["Review_stemmed"] = df["Review"].apply(lambda text: stem_words(text))
df.head()

,Review,Review_stemmed
0,"The ambience was good, food was quite good . h...","the ambienc wa good, food wa quit good . had s..."
1,Ambience is too good for a pleasant evening. S...,ambienc is too good for a pleasant evening. se...
2,A must try.. great food great ambience. Thnx f...,a must try.. great food great ambience. thnx f...
3,Soumen das and Arun was a great guy. Only beca...,soumen da and arun wa a great guy. onli becaus...
4,Food is good.we ordered Kodi drumsticks and ba...,food is good.w order kodi drumstick and basket...

#Lemmatization

In [ ]:
from nltk.stem.snowball import SnowballStemmer
SnowballStemmer.languages

('arabic',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'hungarian',
 'italian',
 'norwegian',
 'porter',
 'portuguese',
 'romanian',
 'russian',
 'spanish',
 'swedish')

In [ ]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
 import nltk
 nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Unzipping corpora/omw-1.4.zip.

True

# New Section

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["Review_lemmatized"] = df["Review"].apply(lambda text: lemmatize_words(text))
df.head(20)

In [ ]:
lemmatizer.lemmatize("reading")

'reading'

In [ ]:
lemmatizer.lemmatize("reading", "v")

'read'

In [ ]:
print("Word is : stripes")
print("Lemma result for verb : ",lemmatizer.lemmatize("stripes", 'v'))
print("Lemma result for noun : ",lemmatizer.lemmatize("stripes", 'n'))

Word is : stripes
Lemma result for verb :  strip
Lemma result for noun :  stripe

In [ ]:
nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
wordnet_map = {"N":wordnet.NOUN, "V":wordnet.VERB, "J":wordnet.ADJ, "R":wordnet.ADV}
def lemmatize_words(text):
    pos_tagged_text = nltk.pos_tag(text.split())
    return " ".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_tagged_text])

df["Review_lemmatized"] = df["Review"].apply(lambda text: lemmatize_words(text))
df.head()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

,Review,Review_stemmed,Review_lemmatized
0,"The ambience was good, food was quite good . h...","the ambienc wa good, food wa quit good . had s...","The ambience be good, food be quite good . hav..."
1,Ambience is too good for a pleasant evening. S...,ambienc is too good for a pleasant evening. se...,Ambience be too good for a pleasant evening. S...
2,A must try.. great food great ambience. Thnx f...,a must try.. great food great ambience. thnx f...,A must try.. great food great ambience. Thnx f...
3,Soumen das and Arun was a great guy. Only beca...,soumen da and arun wa a great guy. onli becaus...,Soumen da and Arun be a great guy. Only becaus...
4,Food is good.we ordered Kodi drumsticks and ba...,food is good.w order kodi drumstick and basket...,Food be good.we ordered Kodi drumstick and bas...